import type { Difficulty, Puzzle } from "./types";

export const PUZZLES: Record<Difficulty, Puzzle[]> = {
  "5x5": [
    {
      id: "5-1",
      name: "Starter",
      rows: 5,
      cols: 5,
      clues: [
        { row: 0, col: 1, value: 4 },
        { row: 1, col: 2, value: 6 },
        { row: 2, col: 3, value: 3 },
        { row: 3, col: 2, value: 2 },
        { row: 4, col: 0, value: 2 },
        { row: 4, col: 1, value: 3 },
        { row: 4, col: 4, value: 5 },
      ],
    },
    {
      id: "5-2",
      name: "Paths",
      rows: 5,
      cols: 5,
      clues: [
        { row: 0, col: 0, value: 5 },
        { row: 1, col: 4, value: 2 },
        { row: 2, col: 2, value: 2 },
        { row: 2, col: 4, value: 2 },
        { row: 3, col: 2, value: 2 },
        { row: 3, col: 3, value: 2 },
        { row: 4, col: 0, value: 8 },
        { row: 4, col: 4, value: 2 },
      ],
    },
    {
      id: "5-3",
      name: "Split",
      rows: 5,
      cols: 5,
      clues: [
        { row: 1, col: 2, value: 9 },
        { row: 1, col: 3, value: 2 },
        { row: 2, col: 3, value: 2 },
        { row: 2, col: 4, value: 3 },
        { row: 3, col: 2, value: 3 },
        { row: 4, col: 0, value: 4 },
        { row: 4, col: 4, value: 2 },
      ],
    },
    {
      id: "5-4",
      name: "Nest",
      rows: 5,
      cols: 5,
      clues: [
        { row: 0, col: 4, value: 5 },
        { row: 2, col: 0, value: 8 },
        { row: 3, col: 4, value: 4 },
        { row: 4, col: 0, value: 2 },
        { row: 4, col: 3, value: 6 },
      ],
    },
    {
      id: "5-5",
      name: "Cross",
      rows: 5,
      cols: 5,
      clues: [
        { row: 0, col: 0, value: 6 },
        { row: 0, col: 4, value: 4 },
        { row: 2, col: 2, value: 5 },
        { row: 3, col: 0, value: 4 },
        { row: 4, col: 4, value: 6 },
      ],
    },
    {
      id: "5-6",
      name: "Tower",
      rows: 5,
      cols: 5,
      clues: [
        { row: 0, col: 0, value: 5 },
        { row: 0, col: 2, value: 8 },
        { row: 2, col: 1, value: 4 },
        { row: 2, col: 4, value: 4 },
        { row: 4, col: 2, value: 4 },
      ],
    },
    {
      id: "5-7",
      name: "Frame",
      rows: 5,
      cols: 5,
      clues: [
        { row: 0, col: 2, value: 5 },
        { row: 1, col: 0, value: 6 },
        { row: 1, col: 3, value: 6 },
        { row: 4, col: 0, value: 2 },
        { row: 4, col: 3, value: 6 },
      ],
    },
  ],
  "7x7": [
    {
      id: "7-1",
      name: "Classic",
      rows: 7,
      cols: 7,
      clues: [
        { row: 1, col: 2, value: 10 },
        { row: 2, col: 1, value: 12 },
        { row: 2, col: 4, value: 2 },
        { row: 3, col: 6, value: 4 },
        { row: 4, col: 2, value: 6 },
        { row: 5, col: 3, value: 4 },
        { row: 5, col: 4, value: 3 },
        { row: 5, col: 5, value: 3 },
        { row: 6, col: 0, value: 2 },
        { row: 6, col: 5, value: 3 },
      ],
    },
    {
      id: "7-2",
      name: "Ridge",
      rows: 7,
      cols: 7,
      clues: [
        { row: 0, col: 0, value: 4 },
        { row: 1, col: 3, value: 8 },
        { row: 1, col: 4, value: 3 },
        { row: 2, col: 1, value: 10 },
        { row: 2, col: 6, value: 6 },
        { row: 3, col: 4, value: 4 },
        { row: 4, col: 5, value: 3 },
        { row: 5, col: 3, value: 2 },
        { row: 5, col: 6, value: 3 },
        { row: 6, col: 2, value: 4 },
        { row: 6, col: 6, value: 2 },
      ],
    },
    {
      id: "7-3",
      name: "Pools",
      rows: 7,
      cols: 7,
      clues: [
        { row: 1, col: 6, value: 4 },
        { row: 2, col: 3, value: 12 },
        { row: 2, col: 5, value: 12 },
        { row: 3, col: 1, value: 4 },
        { row: 3, col: 2, value: 4 },
        { row: 5, col: 0, value: 2 },
        { row: 5, col: 1, value: 2 },
        { row: 5, col: 3, value: 4 },
        { row: 5, col: 6, value: 3 },
        { row: 6, col: 5, value: 2 },
      ],
    },
    {
      id: "7-4",
      name: "Weave",
      rows: 7,
      cols: 7,
      clues: [
        { row: 1, col: 2, value: 10 },
        { row: 2, col: 2, value: 4 },
        { row: 2, col: 4, value: 4 },
        { row: 3, col: 0, value: 6 },
        { row: 4, col: 3, value: 6 },
        { row: 4, col: 5, value: 10 },
        { row: 5, col: 0, value: 4 },
        { row: 5, col: 6, value: 2 },
        { row: 6, col: 4, value: 3 },
      ],
    },
    {
      id: "7-5",
      name: "Corner",
      rows: 7,
      cols: 7,
      clues: [
        { row: 1, col: 1, value: 9 },
        { row: 0, col: 5, value: 8 },
        { row: 2, col: 4, value: 4 },
        { row: 3, col: 1, value: 6 },
        { row: 4, col: 3, value: 8 },
        { row: 6, col: 1, value: 6 },
        { row: 5, col: 6, value: 8 },
      ],
    },
    {
      id: "7-6",
      name: "Steps",
      rows: 7,
      cols: 7,
      clues: [
        { row: 0, col: 1, value: 8 },
        { row: 1, col: 5, value: 9 },
        { row: 2, col: 2, value: 8 },
        { row: 3, col: 5, value: 6 },
        { row: 4, col: 2, value: 8 },
        { row: 6, col: 5, value: 6 },
        { row: 6, col: 2, value: 4 },
      ],
    },
    {
      id: "7-7",
      name: "Bands",
      rows: 7,
      cols: 7,
      clues: [
        { row: 0, col: 2, value: 8 },
        { row: 1, col: 5, value: 12 },
        { row: 2, col: 1, value: 8 },
        { row: 5, col: 0, value: 6 },
        { row: 5, col: 3, value: 9 },
        { row: 6, col: 6, value: 6 },
      ],
    },
  ],
  "9x9": [
    {
      id: "9-1",
      name: "Grand",
      rows: 9,
      cols: 9,
      clues: [
        { row: 0, col: 1, value: 4 },
        { row: 0, col: 4, value: 4 },
        { row: 1, col: 4, value: 6 },
        { row: 1, col: 7, value: 3 },
        { row: 1, col: 8, value: 4 },
        { row: 5, col: 3, value: 4 },
        { row: 6, col: 0, value: 18 },
        { row: 6, col: 5, value: 14 },
        { row: 7, col: 1, value: 2 },
        { row: 7, col: 4, value: 4 },
        { row: 7, col: 7, value: 5 },
        { row: 7, col: 8, value: 5 },
        { row: 8, col: 0, value: 2 },
        { row: 8, col: 4, value: 6 },
      ],
    },
    {
      id: "9-2",
      name: "Fields",
      rows: 9,
      cols: 9,
      clues: [
        { row: 1, col: 1, value: 18 },
        { row: 1, col: 6, value: 12 },
        { row: 2, col: 5, value: 15 },
        { row: 4, col: 7, value: 12 },
        { row: 5, col: 4, value: 4 },
        { row: 6, col: 0, value: 2 },
        { row: 7, col: 1, value: 2 },
        { row: 7, col: 2, value: 3 },
        { row: 7, col: 4, value: 2 },
        { row: 7, col: 5, value: 3 },
        { row: 8, col: 1, value: 2 },
        { row: 8, col: 7, value: 6 },
      ],
    },
    {
      id: "9-3",
      name: "Rings",
      rows: 9,
      cols: 9,
      clues: [
        { row: 0, col: 2, value: 2 },
        { row: 0, col: 3, value: 14 },
        { row: 0, col: 8, value: 4 },
        { row: 1, col: 1, value: 6 },
        { row: 2, col: 5, value: 9 },
        { row: 3, col: 0, value: 2 },
        { row: 3, col: 2, value: 2 },
        { row: 5, col: 1, value: 6 },
        { row: 5, col: 5, value: 6 },
        { row: 6, col: 7, value: 10 },
        { row: 7, col: 3, value: 4 },
        { row: 7, col: 8, value: 5 },
        { row: 8, col: 1, value: 9 },
        { row: 8, col: 7, value: 2 },
      ],
    },
    {
      id: "9-4",
      name: "Delta",
      rows: 9,
      cols: 9,
      clues: [
        { row: 1, col: 2, value: 20 },
        { row: 4, col: 0, value: 5 },
        { row: 4, col: 6, value: 20 },
        { row: 6, col: 1, value: 18 },
        { row: 6, col: 8, value: 9 },
        { row: 8, col: 1, value: 3 },
        { row: 8, col: 4, value: 2 },
        { row: 8, col: 5, value: 2 },
        { row: 8, col: 8, value: 2 },
      ],
    },
    {
      id: "9-5",
      name: "Basin",
      rows: 9,
      cols: 9,
      clues: [
        { row: 1, col: 1, value: 9 },
        { row: 0, col: 5, value: 12 },
        { row: 3, col: 4, value: 9 },
        { row: 2, col: 7, value: 3 },
        { row: 4, col: 7, value: 9 },
        { row: 4, col: 1, value: 9 },
        { row: 6, col: 4, value: 9 },
        { row: 7, col: 7, value: 9 },
        { row: 7, col: 1, value: 9 },
        { row: 8, col: 4, value: 3 },
      ],
    },
    {
      id: "9-6",
      name: "Stripes",
      rows: 9,
      cols: 9,
      clues: [
        { row: 4, col: 0, value: 9 },
        { row: 2, col: 1, value: 10 },
        { row: 6, col: 1, value: 8 },
        { row: 1, col: 4, value: 9 },
        { row: 4, col: 3, value: 6 },
        { row: 5, col: 5, value: 6 },
        { row: 7, col: 3, value: 6 },
        { row: 2, col: 7, value: 15 },
        { row: 6, col: 7, value: 12 },
      ],
    },
    {
      id: "9-7",
      name: "Tiles",
      rows: 9,
      cols: 9,
      clues: [
        { row: 1, col: 1, value: 12 },
        { row: 1, col: 6, value: 15 },
        { row: 4, col: 1, value: 9 },
        { row: 4, col: 4, value: 9 },
        { row: 4, col: 7, value: 9 },
        { row: 7, col: 1, value: 9 },
        { row: 7, col: 4, value: 9 },
        { row: 7, col: 7, value: 9 },
      ],
    },
  ],
  "10x10": [
    {
      id: "10-1",
      name: "Deca",
      rows: 10,
      cols: 10,
      clues: [
        { row: 3, col: 6, value: 16 },
        { row: 4, col: 6, value: 8 },
        { row: 5, col: 8, value: 2 },
        { row: 6, col: 0, value: 24 },
        { row: 6, col: 5, value: 5 },
        { row: 7, col: 4, value: 20 },
        { row: 7, col: 8, value: 3 },
        { row: 8, col: 1, value: 2 },
        { row: 8, col: 6, value: 2 },
        { row: 8, col: 9, value: 9 },
        { row: 9, col: 0, value: 2 },
        { row: 9, col: 2, value: 2 },
        { row: 9, col: 7, value: 3 },
        { row: 9, col: 9, value: 2 },
      ],
    },
    {
      id: "10-2",
      name: "Walls",
      rows: 10,
      cols: 10,
      clues: [
        { row: 0, col: 2, value: 21 },
        { row: 0, col: 9, value: 2 },
        { row: 2, col: 3, value: 20 },
        { row: 3, col: 7, value: 10 },
        { row: 3, col: 9, value: 2 },
        { row: 5, col: 8, value: 3 },
        { row: 5, col: 9, value: 4 },
        { row: 6, col: 6, value: 25 },
        { row: 8, col: 1, value: 9 },
        { row: 8, col: 9, value: 2 },
        { row: 9, col: 9, value: 2 },
      ],
    },
    {
      id: "10-3",
      name: "Lanes",
      rows: 10,
      cols: 10,
      clues: [
        { row: 0, col: 1, value: 8 },
        { row: 1, col: 4, value: 20 },
        { row: 1, col: 8, value: 4 },
        { row: 2, col: 2, value: 5 },
        { row: 2, col: 3, value: 4 },
        { row: 4, col: 9, value: 6 },
        { row: 5, col: 1, value: 8 },
        { row: 7, col: 2, value: 3 },
        { row: 7, col: 3, value: 2 },
        { row: 7, col: 5, value: 12 },
        { row: 8, col: 0, value: 8 },
        { row: 9, col: 5, value: 10 },
        { row: 9, col: 8, value: 8 },
        { row: 9, col: 9, value: 2 },
      ],
    },
    {
      id: "10-4",
      name: "Blocks",
      rows: 10,
      cols: 10,
      clues: [
        { row: 0, col: 2, value: 15 },
        { row: 0, col: 9, value: 8 },
        { row: 1, col: 0, value: 9 },
        { row: 2, col: 7, value: 9 },
        { row: 3, col: 7, value: 3 },
        { row: 4, col: 4, value: 15 },
        { row: 4, col: 7, value: 2 },
        { row: 5, col: 8, value: 4 },
        { row: 6, col: 7, value: 2 },
        { row: 7, col: 2, value: 4 },
        { row: 7, col: 3, value: 6 },
        { row: 7, col: 6, value: 4 },
        { row: 8, col: 1, value: 9 },
        { row: 9, col: 9, value: 10 },
      ],
    },
    {
      id: "10-6",
      name: "Quad",
      rows: 10,
      cols: 10,
      clues: [
        { row: 1, col: 2, value: 20 },
        { row: 1, col: 7, value: 15 },
        { row: 3, col: 7, value: 10 },
        { row: 5, col: 2, value: 15 },
        { row: 7, col: 7, value: 25 },
        { row: 8, col: 2, value: 15 },
      ],
    },
    {
      id: "10-7",
      name: "Mosaic",
      rows: 10,
      cols: 10,
      clues: [
        { row: 1, col: 1, value: 9 },
        { row: 0, col: 5, value: 10 },
        { row: 1, col: 9, value: 8 },
        { row: 2, col: 5, value: 10 },
        { row: 4, col: 1, value: 9 },
        { row: 5, col: 5, value: 12 },
        { row: 5, col: 8, value: 12 },
        { row: 7, col: 1, value: 12 },
        { row: 8, col: 4, value: 12 },
        { row: 9, col: 8, value: 6 },
      ],
    },
    {
      id: "10-8",
      name: "Zigzag",
      rows: 10,
      cols: 10,
      clues: [
        { row: 2, col: 0, value: 10 },
        { row: 1, col: 3, value: 12 },
        { row: 1, col: 8, value: 16 },
        { row: 3, col: 4, value: 8 },
        { row: 7, col: 0, value: 10 },
        { row: 5, col: 8, value: 12 },
        { row: 6, col: 3, value: 12 },
        { row: 8, col: 8, value: 12 },
        { row: 9, col: 4, value: 8 },
      ],
    },
    {
      id: "10-5",
      name: "Merge",
      rows: 10,
      cols: 10,
      clues: [
        { row: 1, col: 1, value: 18 },
        { row: 2, col: 2, value: 20 },
        { row: 2, col: 7, value: 24 },
        { row: 5, col: 5, value: 2 },
        { row: 6, col: 3, value: 6 },
        { row: 7, col: 4, value: 3 },
        { row: 7, col: 9, value: 2 },
        { row: 8, col: 3, value: 3 },
        { row: 8, col: 5, value: 3 },
        { row: 9, col: 3, value: 5 },
        { row: 9, col: 6, value: 12 },
        { row: 9, col: 9, value: 2 },
      ],
    }
  ],
};

export function getRandomPuzzle(difficulty: Difficulty, excludeId?: string): Puzzle {
  const pool = PUZZLES[difficulty].filter((p) => p.id !== excludeId);
  const list = pool.length > 0 ? pool : PUZZLES[difficulty];
  return list[Math.floor(Math.random() * list.length)];
}
